# class labels
classes = {
    0: "Speedlimit = 20",
    1: "Speedlimit = 30",
    2: "Speedlimit = 50",
    3: "Speedlimit = 60",
    4: "Speedlimit = 70",
    5: "Speedlimit = 80",
    6: "End of Speedlimit = 80",
    7: "End of Speedlimit = 100",
    8: "Speedlimit = 120",
    9: "No overtaking allowed for cars",
    10: "No overtaking allowed for trucks",
    11: "Right of way at next junction",
    12: "Right of way on this road",
    13: "Yield right of way",
    14: "Stop. Yield right of way",
    15: "All vehicles banned for this road",
    16: "All trucks banned for this road",
    17: "No Entry!",
    18: "Danger Spot",
    19: "Sharp Left Corner",
    20: "Sharp Right Corner",
    21: "Double Curve",
    22: "Uneven Road",
    23: "Slip Hazard",
    24: "Road narrows",
    25: "Roadworks",
    26: "Traffic Light",
    27: "Pedestrians",
    28: "Children",
    29: "Cyclists",
    30: "Slipperiness",
    31: "Deer Path",
    32: "End of all constraints",
    33: "Prescribed driving direction right",
    34: "Prescribed driving direction left",
    35: "Prescribed driving direction ahead",
    36: "Prescribed driving direction ahead and right",
    37: "Prescribed driving direction ahead and left",
    38: "Prescribed passing at the right side",
    39: "Prescribed passing at the left side",
    40: "Roundabout",
    41: "Overtaking is now allowed",
    42: "Overtaking is now allowed for trucks",
}
